Fix socketio version for node6 (#1493)
## What does this PR do ?

Latest version of `socket.io` have dependencies that does not support Node.js 6 anymore 
```
SyntaxError: Unexpected token ...
/home/aschen/projets/kuzzleio/kuzzle-1.x/node_modules/engine.io/node_modules/ws/lib/websocket.js:347
      ...options
      ^^^

```